# simplicity always recommend to name the playbook
  name: install and start apache
  tasks:
    - name: install apache packages
      yum:
        name: httpd
        state: latest
    - name: start apache service
      services:
        name: httpd
        state: started
        enabled: yes